# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visited',
            new_name='visitors_counter',
        ),
    ]
