# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170408_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visitors_counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
